name: Manual Psych Engine HTML5 Build

on:
  workflow_dispatch:

jobs:
  build-html5:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (with tags)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch full history including tags

      - name: Checkout tag 0.6.2
        run: git checkout tags/0.6.2

      - name: Set up Haxe 4.2.2
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: '4.2.2'

      - name: Install required haxelibs
        run: |
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib install flixel 4.9.0
          haxelib install flixel-addons 3.2.2
          haxelib install flixel-ui 2.3.3
          haxelib install flixel-tools 1.5.1
          haxelib install tjson 1.4.0
          haxelib install hxjsonast 1.1.0
          haxelib install hscript 2.4.0
          haxelib install hxcodec 2.5.1
          haxelib run lime setup
          haxelib run flixel-tools setup

      - name: Build HTML5
        run: lime test html5

      - name: Upload HTML5 Build
        uses: actions/upload-artifact@v4
        with:
          name: html5-build
          path: export/html5/
          retention-days: 90
