name: Manual Psych Engine HTML5 Build

on:
  workflow_dispatch:

jobs:
  build-html5:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code (with tags)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout tag 0.6.2
        run: git checkout tags/0.6.2

      - name: Set up Haxe 4.2.2
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: '4.2.2'

      - name: Install required haxelibs
        run: |
          haxelib install lime 7.9.0
          haxelib set lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib set openfl 9.1.0
          haxelib install flixel 4.9.0
          haxelib install flixel-addons 2.11.0
          haxelib install flixel-ui 2.3.3
          haxelib install flixel-tools 1.5.1
          haxelib install tjson 1.4.0
          haxelib install hxjsonast 1.1.0
          haxelib install hscript 2.4.0
          haxelib install hxcodec 2.5.1
          haxelib run lime setup

      - name: Install libffi.so.6 (required for Lime webify)
        run: |
          sudo apt-get update
          sudo apt-get install -y libffi6 || (
            echo "libffi6 not found, manually downloading..."
            wget http://archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
            sudo dpkg -i libffi6_3.2.1-8_amd64.deb
          )

      - name: Build HTML5 (release + verbose)
        run: haxelib run lime build html5  -verbose

      - name: Upload HTML5 Build
        uses: actions/upload-artifact@v4
        with:
          name: html5-build
          path: export/html5/
          retention-days: 90
